
server:
  port: 8082

spring:
  application:
    name: ClientService
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/testdb
#    username: root
#    password: pass@word1
#  datasource:
#    url: jdbc:postgresql://localhost:5432/event
#    username: postgres
#    password: postgres
#    driver-class-name: org.postgresql.Driver
  datasource:
    url: jdbc:mysql://localhost:3306/testdb #event
    username: root
    password: pass@word1
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

